set_property PACKAGE_PIN R14 [get_ports LED0]
set_property PACKAGE_PIN P14 [get_ports LED1]
set_property PACKAGE_PIN N16 [get_ports LED2]
set_property PACKAGE_PIN M14 [get_ports LED3]
set_property PACKAGE_PIN L15 [get_ports LED4_b]
set_property PACKAGE_PIN M15 [get_ports LED5_b]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports LED5_b]
set_property IOSTANDARD LVCMOS33 [get_ports LED4_b]
set_property IOSTANDARD LVCMOS33 [get_ports clk_125]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports AC_MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO3]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO2]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO1]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR1]
set_property PACKAGE_PIN U9 [get_ports AC_SCK]
set_property PACKAGE_PIN T9 [get_ports AC_SDA]
set_property PULLUP true [get_ports AC_SDA]
set_property PULLUP true [get_ports AC_SCK]
set_property PACKAGE_PIN U5 [get_ports AC_MCLK]
set_property PACKAGE_PIN H16 [get_ports clk_125]
set_property PACKAGE_PIN R18 [get_ports AC_GPIO2]
set_property PACKAGE_PIN T17 [get_ports AC_GPIO3]
set_property PACKAGE_PIN M17 [get_ports AC_ADR0]
set_property PACKAGE_PIN M18 [get_ports AC_ADR1]
set_property PACKAGE_PIN G18 [get_ports AC_GPIO0]
set_property PACKAGE_PIN F17 [get_ports AC_GPIO1]

create_clock -period 10.000 -name CLK_100 -waveform {0.000 5.000} -add [get_nets clk_100]
create_clock -period 33.000 -name CLK_30 -waveform {0.000 16.500} -add [get_nets clk_25]
create_clock -period 20833.000 -name CLK_48k -waveform {0.000 10416.500} -add [get_nets audio_top0/clk_48]
create_clock -period 66.000 -name CLK_15 -waveform {0.000 33.000} -add [get_nets SignalPreAnalysisU0/div_clk]
create_clock -period 125.000 -name CLK_8 -waveform {0.000 62.500} -add [get_nets SignalPreAnalysisU0/divdiv_clk]