set_property PACKAGE_PIN R14 [get_ports LED0]
set_property PACKAGE_PIN P14 [get_ports LED1]
set_property PACKAGE_PIN N16 [get_ports LED2]
set_property PACKAGE_PIN M14 [get_ports LED3]
set_property PACKAGE_PIN L15 [get_ports LED4_b]
set_property PACKAGE_PIN L14 [get_ports LED5_b]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports LED5_b]
set_property IOSTANDARD LVCMOS33 [get_ports LED4_b]
set_property IOSTANDARD LVCMOS33 [get_ports clk_125]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports AC_MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO3]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO2]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO1]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR1]
set_property PACKAGE_PIN U9 [get_ports AC_SCK]
set_property PACKAGE_PIN T9 [get_ports AC_SDA]
set_property PULLUP true [get_ports AC_SDA]
set_property PULLUP true [get_ports AC_SCK]
set_property PACKAGE_PIN U5 [get_ports AC_MCLK]
set_property PACKAGE_PIN H16 [get_ports clk_125]
set_property PACKAGE_PIN R18 [get_ports AC_GPIO2]
set_property PACKAGE_PIN T17 [get_ports AC_GPIO3]
set_property PACKAGE_PIN M17 [get_ports AC_ADR0]
set_property PACKAGE_PIN M18 [get_ports AC_ADR1]
set_property PACKAGE_PIN G18 [get_ports AC_GPIO0]
set_property PACKAGE_PIN F17 [get_ports AC_GPIO1]


create_generated_clock -name SignalPreAnalysisU0/div_clk -source [get_pins clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0] -divide_by 2 [get_pins SignalPreAnalysisU0/div_clk_reg/Q]
set_false_path -from [get_clocks -of_objects [get_pins audio_top0/i_clocking/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins audio_top0/i_clocking/mmcm_adv_inst/CLKOUT0]]

create_generated_clock -name SignalPreAnalysisU0/divdiv_clk_reg_n_0 -source [get_pins SignalPreAnalysisU0/div_clk_reg/Q] -divide_by 2 [get_pins SignalPreAnalysisU0/divdiv_clk_reg/Q]
create_generated_clock -name sample_clk_48k -source [get_pins clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1] -divide_by 2083 [get_pins audio_top0/sample_clk_48k_reg/Q]
set_clock_groups -asynchronous -group [get_clocks sample_clk_48k] -group [get_clocks SignalPreAnalysisU0/div_clk]
